name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        env:
            DATABASE_HOSTNAME: localhost
            DATABASE_PORT: 5432
            DATABASE_PASSWORD: chidera123
            DATABASE_NAME: myfastapi
            DATABASE_USERNAME: postgres
            SECRET_KEY: 8006e3b9959a542980d4d1ebfc2e1900bfc33a2ed720ea34155c904b0b4d8ce6
            ALGORITHM: HS256
            ACCESS_TOKEN_EXPIRE_MINUTES: 15
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repository
              uses: actions/checkout@v6

            - name: Say hi to user
              run: echo "Hi, ${{ github.actor }}! Welcome to the build and deploy workflow."
            
            - name: Install python version 13
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
            
            - name: update pip
              run: python -m pip install --upgrade pip

            - name: Install all dependencies
              run: pip install -r requirements.txt

            - name: Run the test with pytest
              run: |
                pip install pytest
                pytest
