name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repository
              uses: actions/checkout@v6
            - name: Say hi to user
              run: echo "Hi, ${{ github.actor }}! Welcome to the build and deploy workflow."